name: Daily ETF Data Update

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        # cloudscraper가 추가되었습니다!
        run: |
          pip install pandas requests lxml html5lib cloudscraper

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data.json
          git commit -m "Update ETF data" || exit 0
          git push
